---

# Configure nginx vhosts
nginx_custom_vhosts:
  - port: "{{ nginx_port }}"
    server_name: "{{ ansible_host }}"
    root: "{{ nginx_default_root }}"
    access_log: /var/log/nginx/default.access.log
    error_log: /var/log/nginx/default.error.log
    active_php: yes
    front_controller: index
    index: index.html index.php
    strip_prefix: no
    rewrites: no
    misc: |
           # Add here some custom stuff for your nginx vhost config
  - port: "{{ nginx_port }}"
    server_name: sulu.local
    root: /srv/www/sulu/web
    access_log: /var/log/nginx/sulu.local.access.log
    error_log: /var/log/nginx/sulu.local.error.log
    strip_prefix: app\.php
    active_php: yes
    front_controller: website|admin|app|app_dev|config
    index: no
    rewrites:
      - name: admin
        location: /admin
        index: admin.php
      - name: website
        location: /
        index: website.php
