---

# Consul services definitions
consul_services:
  - name: api-platform
    check:
      interval: 10s
      script: "docker ps | grep -e 'srv_web' && docker ps | grep srv_database && (echo 'OK'; exit 0) || (echo 'KO';exit 1)"
    port: 8000
    tags:
      - web

consul_checks:
  - name: Health - ping
    interval: 30s
    script: "ping -c1 google.com"
  - name: Health - docker
    interval: 30s
    script: "docker ps"
    tags:
      - docker
  - name: Health - supervisor
    interval: 30s
    script: "supervisorctl status"
    tags:
      - supervisor
