---

# Include Base playbook for common tasks
- include: base.yml

# Specific playbook for go servers, including MongoDB for projects needs
- hosts: goservers
  become: true
  become_method: sudo
  roles:
    - { role: go, tags: ['golang'] }
    - { role: mongodb, tags: ['go', 'mongodb'] }
    - { role: supervisor, tags: ['go', 'supervisor'] }