---


supervisor_http_host: "localhost"

# supervisor programs configuration
supervisor_programs:
  statsd:
    command: "/usr/bin/nodejs stats.js {{ statsd_config_path }}/config.js"
    directory: "{{ statsd_install_path }}"
    autostart: "true"
    autorestart: "true"
    stderr_logfile: "{{ supervisor_log_path }}/statsd-stderr.log"
    stderr_logfile_maxbytes: 1MB
    stderr_logfile_backups: 10
    stdout_logfile: "{{ supervisor_log_path }}/statsd-stdout.log"
    stdout_logfile_maxbytes: 1MB
    stdout_logfile_backups: 10
    user: "{{ statsd_user }}"
  mailhog:
    command: /usr/local/bin/mailhog -api-bind-addr :8025 -ui-bind-addr :8025
    autostart: "true"
    autorestart: "true"
    stderr_logfile: "{{ supervisor_log_path }}/mailhog-stderr.log"
  supervisor_events:
    httpok:
    command: httpok -p mailhog http://localhost:8025
    events: TICK_60
